# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CTC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from CTCoffice import CTCoffice
from PyQt5 import QtCore, QtGui, QtWidgets
from testUI import testUI
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class mainUI(QMainWindow):

    def __init__(self, ctc: CTCoffice, olist: [], numtrains: int, track: [], station: []):
        super().__init__()

        self.station = station
        self.officeList = olist
        self.CTCoffice = ctc
        self.numTrains = numtrains
        self.track = track
        self.trackSymbol = {1: "🟢", 2: "🟡", 0: "🔴"}

        self.setupUi()
        self.show()


    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(957, 724)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(170, 30, 621, 251))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 841, 591))
        self.groupBox.setObjectName("groupBox")
        self.tab_Mode = QtWidgets.QTabWidget(self.groupBox)
        self.tab_Mode.setGeometry(QtCore.QRect(100, 300, 721, 261))
        self.tab_Mode.setObjectName("tab_Mode")
        self.Automatic = QtWidgets.QWidget()
        self.Automatic.setObjectName("Automatic")
        self.label = QtWidgets.QLabel(self.Automatic)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Automatic)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Automatic)
        self.label_3.setGeometry(QtCore.QRect(520, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.autoTable = QtWidgets.QTableWidget(self.Automatic)
        self.autoTable.setGeometry(QtCore.QRect(10, 50, 301, 151))
        self.autoTable.setObjectName("autoTable")
        self.autoTable.setColumnCount(3)
        self.autoTable.setRowCount(0)
        self.autoTable.setColumnWidth(0, 90)
        self.autoTable.setColumnWidth(1, 100)
        self.autoTable.setColumnWidth(2, 100)

        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(2, item)
        self.auto2table = QtWidgets.QTableWidget(self.Automatic)
        self.auto2table.setGeometry(QtCore.QRect(320, 50, 191, 151))
        self.auto2table.setObjectName("auto2table")
        self.auto2table.setColumnCount(2)
        self.auto2table.setRowCount(0)
        self.auto2table.setColumnWidth(0, 90)
        self.auto2table.setColumnWidth(1, 90)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.auto2table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignVCenter)
        self.auto2table.setHorizontalHeaderItem(1, item)
        self.auto3table = QtWidgets.QTableWidget(self.Automatic)
        self.auto3table.setGeometry(QtCore.QRect(520, 50, 191, 151))
        self.auto3table.setObjectName("auto3table")
        self.auto3table.setColumnCount(2)
        self.auto3table.setRowCount(0)
        self.auto3table.setColumnWidth(0, 90)
        self.auto3table.setColumnWidth(1, 90)
        item = QtWidgets.QTableWidgetItem()
        self.auto3table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.auto3table.setHorizontalHeaderItem(1, item)
        self.tab_Mode.addTab(self.Automatic, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.timeSelect = QtWidgets.QTimeEdit(self.Manual)
        self.timeSelect.setGeometry(QtCore.QRect(600, 90, 118, 22))
        self.timeSelect.setObjectName("timeSelect")
        self.confirmButton = QtWidgets.QPushButton(self.Manual)
        self.confirmButton.setGeometry(QtCore.QRect(600, 180, 75, 24))
        self.confirmButton.setObjectName("confirmButton")
        self.trainSelect = QtWidgets.QComboBox(self.Manual)
        self.trainSelect.setGeometry(QtCore.QRect(420, 90, 151, 31))
        self.trainSelect.setObjectName("trainSelect")
        self.trainSelect.addItem("")
        self.label_4 = QtWidgets.QLabel(self.Manual)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Manual)
        self.label_5.setGeometry(QtCore.QRect(420, 70, 181, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Manual)
        self.label_6.setGeometry(QtCore.QRect(420, 160, 181, 16))
        self.label_6.setObjectName("label_6")
        self.stationSelect = QtWidgets.QComboBox(self.Manual)
        self.stationSelect.setGeometry(QtCore.QRect(420, 180, 151, 31))
        self.stationSelect.setObjectName("stationSelect")
        self.stationSelect.addItem("1")
        self.stationSelect.addItem("2")
        self.label_7 = QtWidgets.QLabel(self.Manual)
        self.label_7.setGeometry(QtCore.QRect(600, 70, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Manual)
        self.label_8.setGeometry(QtCore.QRect(600, 160, 101, 16))
        self.label_8.setObjectName("label_8")
        self.manualTable = QtWidgets.QTableWidget(self.Manual)
        self.manualTable.setGeometry(QtCore.QRect(10, 90, 390, 120))
        self.manualTable.setObjectName("manualTable")
        self.manualTable.setColumnCount(4)
        self.manualTable.setRowCount(0)
        self.manualTable.setColumnWidth(0, 80)
        self.manualTable.setColumnWidth(1, 90)
        self.manualTable.setColumnWidth(2, 90)
        self.manualTable.setColumnWidth(3, 120)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(3, item)
        self.tab_Mode.addTab(self.Manual, "")
        self.Maintenance = QtWidgets.QWidget()
        self.Maintenance.setObjectName("Maintenance")
        self.maintenanceTable = QtWidgets.QTableWidget(self.Maintenance)
        self.maintenanceTable.setGeometry(QtCore.QRect(10, 50, 401, 171))
        self.maintenanceTable.setObjectName("maintenanceTable")
        self.maintenanceTable.setColumnCount(4)
        self.maintenanceTable.setRowCount(0)
        self.maintenanceTable.setColumnWidth(0, 80)
        self.maintenanceTable.setColumnWidth(1, 110)
        self.maintenanceTable.setColumnWidth(2, 100)
        self.maintenanceTable.setColumnWidth(3, 100)
        self.confirmButton2 = QtWidgets.QPushButton(self.Maintenance)
        self.confirmButton2.setGeometry(QtCore.QRect(610, 165, 75, 24))
        self.confirmButton2.setObjectName("confirmButton2")
        self.label_13 = QtWidgets.QLabel(self.Maintenance)
        self.label_13.setGeometry(QtCore.QRect(610, 145, 181, 16))
        self.label_13.setObjectName("label_13")
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(3, item)
        self.label_10 = QtWidgets.QLabel(self.Maintenance)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.label_10.setObjectName("label_10")
        self.lineSelect = QtWidgets.QComboBox(self.Maintenance)
        self.lineSelect.setGeometry(QtCore.QRect(440, 80, 151, 31))
        self.lineSelect.setObjectName("lineSelect")
        self.lineSelect.addItem("Blue")
        self.lineSelect.addItem("Green")
        self.lineSelect.addItem("Red")

        self.label_11 = QtWidgets.QLabel(self.Maintenance)
        self.label_11.setGeometry(QtCore.QRect(440, 60, 181, 16))
        self.label_11.setObjectName("label_11")
        self.trackSelect = QtWidgets.QComboBox(self.Maintenance)
        self.trackSelect.setGeometry(QtCore.QRect(440, 160, 151, 31))
        self.trackSelect.setObjectName("trackSelect")
        for i in range(1,15):
            self.trackSelect.addItem(str(i))

        self.label_12 = QtWidgets.QLabel(self.Maintenance)
        self.label_12.setGeometry(QtCore.QRect(440, 140, 181, 16))
        self.label_12.setObjectName("label_12")
        self.radioButton = QtWidgets.QRadioButton(self.Maintenance)
        self.radioButton.setGeometry(QtCore.QRect(610, 90, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.tab_Mode.addTab(self.Maintenance, "")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 30, 711, 251))
        self.label_9.setObjectName("label_9")


        self.stationCCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.stationCCount.setGeometry(QtCore.QRect(710, 250, 50, 23))
        self.stationCCount.setObjectName("stationCCount")
        self.stationCCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.stationBCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.stationBCount.setGeometry(QtCore.QRect(660, 90, 50, 23))
        self.stationBCount.setObjectName("stationBCount")
        self.stationBCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.statusLine1 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine1.setGeometry(QtCore.QRect(266, 146, 30, 16))
        self.statusLine1.setObjectName("statusLine1")
        self.statusLine2 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine2.setGeometry(QtCore.QRect(310, 146, 31, 16))
        self.statusLine2.setObjectName("statusLine2")
        self.statusLine3 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine3.setGeometry(QtCore.QRect(360, 140, 31, 30))
        self.statusLine3.setObjectName("statusLine3")
        self.statusLine4 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine4.setGeometry(QtCore.QRect(408, 150, 30, 10))
        self.statusLine4.setObjectName("statusLine4")
        self.statusLine5 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine5.setGeometry(QtCore.QRect(458, 150, 30, 10))
        self.statusLine5.setObjectName("statusLine5")
        self.statusLine9 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine9.setGeometry(QtCore.QRect(621, 89, 30, 10))
        self.statusLine9.setObjectName("statusLine9")
        self.statusLine8 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine8.setGeometry(QtCore.QRect(587, 102, 30, 10))
        self.statusLine8.setObjectName("statusLine8")
        self.statusLine7 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine7.setGeometry(QtCore.QRect(550, 120, 30, 10))
        self.statusLine7.setObjectName("statusLine7")
        self.statusLine6 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine6.setGeometry(QtCore.QRect(512, 132, 30, 10))
        self.statusLine6.setObjectName("statusLine6")
        self.statusLine11 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine11.setGeometry(QtCore.QRect(501, 162, 30, 10))
        self.statusLine11.setObjectName("statusLine11")
        self.statusLine12 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine12.setGeometry(QtCore.QRect(551, 181, 30, 10))
        self.statusLine12.setObjectName("statusLine12")
        self.statusLine13 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine13.setGeometry(QtCore.QRect(608, 199, 30, 10))
        self.statusLine13.setObjectName("statusLine13")
        self.statusLine14 = QtWidgets.QLabel(self.centralwidget)
        self.statusLine14.setGeometry(QtCore.QRect(660, 213, 30, 10))
        self.statusLine14.setObjectName("statusLine14")
        self.groupBox.raise_()
        self.graphicsView.raise_()
        self.label_9.raise_()
        self.stationCCount.raise_()
        self.stationBCount.raise_()
        self.statusLine1.raise_()
        self.statusLine2.raise_()
        self.statusLine3.raise_()
        self.statusLine4.raise_()
        self.statusLine5.raise_()
        self.statusLine9.raise_()
        self.statusLine8.raise_()
        self.statusLine7.raise_()
        self.statusLine6.raise_()
        self.statusLine11.raise_()
        self.statusLine12.raise_()
        self.statusLine13.raise_()
        self.statusLine14.raise_()
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.retranslateUi()
        self.tab_Mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.handler()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tab_Mode.setToolTip(_translate("MainWindow", "<html><head/><body><p>Manual</p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Train Info"))
        self.label_2.setText(_translate("MainWindow", "Station Info"))
        self.label_3.setText(_translate("MainWindow", "Track Info"))
        item = self.autoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Train ID"))
        item = self.autoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current Dest."))
        item = self.autoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arrival Time"))
        item = self.auto2table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Station ID"))
        item = self.auto2table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "# Waiting"))
        item = self.auto3table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Track ID"))
        item = self.auto3table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Automatic), _translate("MainWindow", "Automatic"))
        self.confirmButton.setText(_translate("MainWindow", "PushButton"))
        self.trainSelect.setItemText(0, _translate("MainWindow", "New Train"))
        self.label_4.setText(_translate("MainWindow", "Selection Info"))
        self.label_5.setText(_translate("MainWindow", "Train Select"))
        self.label_6.setText(_translate("MainWindow", "Station Select(Destination)"))
        self.stationSelect.setItemText(0, _translate("MainWindow", "1"))
        self.stationSelect.setItemText(1, _translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "Arrival Time Select"))
        self.label_8.setText(_translate("MainWindow", "Confirm Changes"))
        item = self.manualTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Train ID"))
        item = self.manualTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current Dest"))
        item = self.manualTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Dest"))
        item = self.manualTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Arrival Time"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Manual), _translate("MainWindow", "Manual"))
        self.confirmButton2.setText(_translate("MainWindow", "PushButton"))
        item = self.maintenanceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Line"))
        item = self.maintenanceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Track ID"))
        item = self.maintenanceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.maintenanceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Status"))
        self.label_10.setText(_translate("MainWindow", "Selection Info"))
        self.lineSelect.setItemText(0, _translate("MainWindow", "Blue"))
        self.lineSelect.setItemText(1, _translate("MainWindow", "Green"))
        self.label_11.setText(_translate("MainWindow", "Line Select"))
        for i in range(14):
            self.trackSelect.setItemText(i, _translate("MainWindow", str(i+1)))

        self.label_12.setText(_translate("MainWindow", "Track Select"))
        self.radioButton.setText(_translate("MainWindow", "Open/Close"))

        self.label_13.setText(_translate("MainWindow", "Confirm Changes"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Maintenance), _translate("MainWindow", "Maintenance"))

        self.label_9.setPixmap(QtGui.QPixmap("blueLIne.png"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.statusLine1.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine2.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine3.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine4.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine5.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine9.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine8.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine7.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine6.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine11.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine12.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine13.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.statusLine14.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.allStatus = [self.statusLine1, self.statusLine2, self.statusLine3, self.statusLine4, self.statusLine5, self.statusLine6, self.statusLine7, self.statusLine8, self.statusLine9, self.statusLine9, self.statusLine11, self.statusLine12, self.statusLine13, self.statusLine14]



        self.stationSelect.activated.connect(self.updateManualTable)
        self.trainSelect.currentIndexChanged.connect(self.updateManualTable)
        self.timeSelect.timeChanged.connect(self.updateManualTable)

        self.lineSelect.activated.connect(self.updateMaintenanceTable)
        self.trackSelect.currentIndexChanged.connect(self.updateMaintenanceTable)
        self.radioButton.clicked.connect(self.updateMaintenanceTable)

        self.confirmButton.clicked.connect(self.updateTrain)
        self.confirmButton2.clicked.connect(self.updateTrack)

    def updateTrack(self):
        track[int(self.trackSelect.currentText()) -1] = self.radioButton.isChecked()
        self.updateAutoTable()
        self.updateTrackStatus()

    def updateCombo(self):
        for i in range(self.trainSelect.count()-1, len(self.officeList)):
            self.trainSelect.addItem(str(i+1))


    def updateTrain(self):
        train = self.trainSelect.currentText()
        destination = self.stationSelect.currentText()
        time = self.timeSelect.time().toString()

        if(train == "New Train"):
            New = CTCoffice()
            New.setTrainID(len(self.officeList)+1)
            New.setDestination(destination)
            New.setArrival_time(str(time))
            self.officeList.append(New)
            self.trainSelect.addItem(str(len(self.officeList)))
            self.updateAutoTable()
        else:
            self.officeList[int(self.trainSelect.currentText())-1].destination = self.stationSelect.currentText()
            self.officeList[int(self.trainSelect.currentText())-1].arrival_time = str(self.timeSelect.time().toString())
            self.updateManualTable()


    def updateMaintenanceTable(self):
        self.maintenanceTable.setRowCount(1)
        self.maintenanceTable.setItem(0, 0, QtWidgets.QTableWidgetItem(str(self.lineSelect.currentText())))
        self.maintenanceTable.setItem(0, 1, QtWidgets.QTableWidgetItem(str(self.trackSelect.currentIndex()+1)))
        self.maintenanceTable.setItem(0, 2, QtWidgets.QTableWidgetItem(str(self.track[int(self.trackSelect.currentIndex())])))
        self.maintenanceTable.setItem(0, 3, QtWidgets.QTableWidgetItem(str(self.radioButton.isChecked())))


    def updateAutoTable(self):
        self.autoTable.setRowCount(len(self.officeList))
        for i in range(len(self.officeList)):
            self.autoTable.setItem(i, 0, QtWidgets.QTableWidgetItem(str(self.officeList[i].train_id)))
            self.autoTable.setItem(i, 1, QtWidgets.QTableWidgetItem(self.officeList[i].destination))
            self.autoTable.setItem(i, 2, QtWidgets.QTableWidgetItem(self.officeList[i].arrival_time))


        self.auto2table.setRowCount(len(self.station))
        for i in range(len(self.station)):
            self.auto2table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(i+1)))
            self.auto2table.setItem(i, 1, QtWidgets.QTableWidgetItem(str(self.station[i])))


        index = []
        count = self.track.count(False)
        self.auto3table.setRowCount(count)
        for x in range(len(self.track)):
            if (not self.track[x]):
                index.append(x+1)
        for x in range(count):
            self.auto3table.setItem(x, 0, QtWidgets.QTableWidgetItem(str(index[x])))
            self.auto3table.setItem(x, 1, QtWidgets.QTableWidgetItem("Closed"))

        self.stationBCount.display(str(self.station[0]))
        self.stationCCount.display(str(self.station[1]))


    def updateManualTable(self):
        self.manualTable.setRowCount(1)
        self.manualTable.setItem(0, 0, QtWidgets.QTableWidgetItem(self.trainSelect.currentText()))
        if(self.trainSelect.currentText() != "New Train"):
            self.manualTable.setItem(0, 1, QtWidgets.QTableWidgetItem(self.officeList[int(self.trainSelect.currentText())-1].destination))
        else:
            self.manualTable.setItem(0, 1, QtWidgets.QTableWidgetItem("NA"))
        self.manualTable.setItem(0, 2, QtWidgets.QTableWidgetItem(self.stationSelect.currentText()))
        self.manualTable.setItem(0, 3, QtWidgets.QTableWidgetItem(self.timeSelect.time().toString()))

        self.autoTable.setRowCount(len(self.officeList))
        for i in range(len(self.officeList)):
            self.autoTable.setItem(i, 0, QtWidgets.QTableWidgetItem(str(self.officeList[i].train_id)))
            self.autoTable.setItem(i, 1, QtWidgets.QTableWidgetItem(self.officeList[i].destination))
            self.autoTable.setItem(i, 2, QtWidgets.QTableWidgetItem(self.officeList[i].arrival_time))

    def updateTrackStatus(self):
        _translate = QtCore.QCoreApplication.translate
        location = []

        for i in range(len(self.officeList)):
            location.append(int(self.officeList[i].location))

        for i in range(len(self.allStatus)):
            if(i == 9):
                continue
            elif(i in location):
                self.allStatus[i-1].setText(_translate("Form", self.trackSymbol[2]))
            else:
                self.allStatus[i].setText(_translate("Form", self.trackSymbol[self.track[i]]))






    def updater(self):
        _translate = QtCore.QCoreApplication.translate
        self.updateAutoTable()
        self.updateCombo()
        self.updateTrackStatus()

    def handler(self):
        self.timer = QTimer(self)
        self.timer.setInterval(100)
        self.timer.timeout.connect(self.updater)
        self.timer.start()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    ctc = CTCoffice()
    olist = []
    numTrains = 0
    track = []
    station = []
    for i in range(1, 17):
        track.append(True)

    station.append(int(0))
    station.append(int(0))

    e = testUI(ctc, olist, numTrains, track, station)
    e1 = mainUI(ctc, olist, numTrains, track, station)

    sys.exit(app.exec_())
